---
title: "Prime analisi"
author: "Mariateresa Russo"
date: "2025-05-31"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(stringr)
library(tm)
library(plotly)
library(ggplot2)
library(igraph)
library(ggraph)
library(tidytext)
library(RColorBrewer)
library(networkD3)

df_new_comments = read.csv("nutrition_comments_cleaned.csv")
df_new_threads = read.csv("nutrition_threads_cleaned.csv")
```

Autori che postano di più e autori che commentano di più
```{r}
# Conteggio thread per autore
threads_by_author <- df_new_threads %>%
  group_by(author) %>%
  summarise(n_threads = n()) %>%
  arrange(desc(n_threads))

threads_by_author

# Conteggio commenti per autore
comments_by_author <- df_new_comments %>%
  group_by(author) %>%
  summarise(n_comments = n()) %>%
  arrange(desc(n_comments))

comments_by_author
```

```{r}
# Prendi i primi 20 autori con più thread
df_top_authors_threads <- threads_by_author %>%
  slice_max(n_threads, n = 20)

# Crea il grafico a barre orizzontali
plot_ly(
  df_top_authors_threads,
  x = ~n_threads,
  y = ~reorder(author, n_threads),
  type = "bar",
  orientation = "h",
  marker = list(color = "orange")
) %>%
  layout(
    title = "Top 20 autori per numero di thread",
    xaxis = list(title = "Numero di thread"),
    yaxis = list(title = "Autori"),
    margin = list(l = 200)
  )

```
```{r}
# Prendi i primi 20 autori con più commenti
df_top_authors_comments <- comments_by_author %>%
  filter(author != "[deleted]") %>%
  slice_max(n_comments, n = 20)

# Crea il grafico a barre orizzontali
plot_ly(
  df_top_authors_comments,
  x = ~n_comments,
  y = ~reorder(author, n_comments),
  type = "bar",
  orientation = "h",
  marker = list(color = "yellow")
) %>%
  layout(
    title = "Top 20 autori per numero di commenti",
    xaxis = list(title = "Numero di commenti"),
    yaxis = list(title = "Autori"),
    margin = list(l = 200)
  )
```


Paarole più frequenti nei titoli
```{r}
library(tidyverse)
library(tidytext)
library(textstem)  
library(stopwords)  

# Lista di verbi ausiliari personalizzata
custom_stopwords <- c("can", "like", "will", "would", "should", "could")

# Tokenizzazione, rimozione stopwords e stemming (lemmatization)
title_words <- df_new_threads %>%
  unnest_tokens(word, title) %>%
  filter(!word %in% stop_words$word) %>%       # rimozione stopwords standard
  filter(!word %in% custom_stopwords) %>%      # rimozione ausiliari personalizzati
  mutate(word = lemmatize_words(word)) %>%     # stemming/lemmatizzazione
  count(word, sort = TRUE) %>%
  filter(n > 5)

p4 <- ggplot(title_words[1:40,], aes(x = reorder(word, n), y = n)) +
  geom_col(fill = "darkorange") +
  coord_flip() +
  labs(title = "Parole più frequenti nei titoli", x = "Parola", y = "Frequenza")
ggplotly(p4)
```

Threads con più score
Score = Upvotes − Downvotes
```{r}
top_threads_by_score <- df_new_threads %>%
  arrange(desc(score)) %>%
  slice_head(n = 30)

plot_ly(top_threads_by_score, 
        x = ~score, 
        y = ~reorder(title, score), 
        type = 'bar', 
        orientation = 'h',
        marker = list(color = 'yellow')) %>%
  layout(title = "Top Thread per Score",
         xaxis = list(title = "Score"),
         yaxis = list(title = ""))
```

Threads con più upvotes
```{r}
top_threads_by_upvotes <- df_new_threads %>%
  arrange(desc(upvotes)) %>%
  slice_head(n = 30)

plot_ly(top_threads_by_upvotes, 
        x = ~upvotes, 
        y = ~reorder(title, upvotes), 
        type = 'bar', 
        orientation = 'h',
        marker = list(color = 'darkorange')) %>%
  layout(title = "Top Thread per Upvotes",
         xaxis = list(title = "Upvotes"),
         yaxis = list(title = ""))

```

parole più frequenti-threads
```{r}
term_freq <- colSums(as.matrix(final_df))
names(term_freq) <- colnames(final_df)
term_freq<- subset(term_freq, term_freq>=20)
df_plot<- data.frame(term = names(term_freq), freq = term_freq)

# Plot word frequency
df_plot<- df_plot %>%
  top_n(30)

ggplot(df_plot, aes(x = reorder(term, +freq), y = freq, fill = freq)) + geom_bar(stat = "identity")+ scale_fill_gradient(low = "orange", high = "red")+ xlab("Terms")+ ylab("Count")+coord_flip()

```

Words cloud-threads
```{r}
suppressWarnings({
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)

matrix <- as.matrix(tdm_df) 
matrix <- t(matrix)
words <- sort(rowSums(matrix),decreasing=TRUE) 
dfw <- data.frame(word = names(words),freq=words)

set.seed(1234) 
wordcloud(words = dfw$word, freq = dfw$freq, min.freq = 1,           
          max.words=1000, random.order=FALSE, rot.per=0.35,            
          colors=brewer.pal(8, "Dark2"))

wordcloud2(data=dfw, size=1.6, color='random-dark', shape='pentagon')
})

```

parole più frequenti-comments
```{r}
term_freq2 <- colSums(as.matrix(final_df2))
names(term_freq2) <- colnames(final_df2)
term_freq2<- subset(term_freq2, term_freq2>=20)
df_plot2<- data.frame(term = names(term_freq2), freq = term_freq2)

# Plot word frequency
df_plot2<- df_plot2 %>%
  top_n(30)

ggplot(df_plot2, aes(x = reorder(term, +freq), y = freq, fill = freq)) + geom_bar(stat = "identity")+ scale_fill_gradient(low = "orange", high = "red")+ xlab("Terms")+ ylab("Count")+coord_flip()

```

Words cloud-comments
```{r}
suppressWarnings({
matrix2 <- as.matrix(tdm_df2) 
matrix2 <- t(matrix2)
words2 <- sort(rowSums(matrix2),decreasing=TRUE) 
dfw2 <- data.frame(word2 = names(words2),freq2 =words2)

set.seed(1234) 
wordcloud(words = dfw2$word2, freq = dfw2$freq2, min.freq = 1,           
          max.words=1000, random.order=FALSE, rot.per=0.35,            
          colors=brewer.pal(8, "Dark2"))

wordcloud2(data=dfw2, size=1.6, color='random-dark', shape='pentagon')
#da nacellare
})
```