---
title: "analisi delle reti"
author: "Enrico D'Orso"
date: "2025-06-02"
output: html_document
---

```{r setup, include=FALSE}
# Librerie necessarie
library(readr)
library(dplyr)
library(stringr)
library(tidytext)


# Caricamento dei dataset puliti
df_new_comments <- read_csv("nutrition_comments_cleaned.csv")
df_new_threads <- read_csv("nutrition_threads_cleaned.csv")

# Estrazione del numero di thread dal comment_id
# Esempio: comment_id "7_1" → thread = 7
df_new_comments <- df_new_comments %>%
  mutate(thread = as.integer(str_extract(comment_id, "^[0-9]+")))

# Creazione della colonna thread_id nei thread in base alla posizione riga
df_new_threads <- df_new_threads %>%
  mutate(thread_id = row_number())

# Join tra commenti e informazioni sui thread
comments_with_threads <- df_new_comments %>%
  left_join(df_new_threads, by = c("thread" = "thread_id"))

# Controllo: mostra prime righe
head(comments_with_threads)

```


Thread → Commento
```{r}

edges_tc <- comments_with_threads %>%
  mutate(Source = paste0("T_", thread),
         Target = paste0("C_", comment_id)) %>%
  select(Source, Target)

nodes_tc <- tibble(Id = unique(c(edges_tc$Source, edges_tc$Target))) %>%
  mutate(
    type = case_when(
      str_starts(Id, "T_") ~ "Thread",
      str_starts(Id, "C_") ~ "Comment"
    ),
    Label = Id
  )

write_csv(edges_tc, "edges_thread_comment.csv")
write_csv(nodes_tc, "nodes_thread_comment.csv")


```

Commento → Sottocommento
```{r}

edges_cc <- comments_with_threads %>%
  filter(str_detect(comment_id, "_")) %>%
  mutate(Source = paste0("C_", str_extract(comment_id, "^[^_]+(?:_[^_]+)?")),
         Target = paste0("C_", comment_id)) %>%
  select(Source, Target)

nodes_cc <- tibble(Id = unique(c(edges_cc$Source, edges_cc$Target))) %>%
  mutate(
    type = "Comment",
    Label = Id
  )

write_csv(edges_cc, "edges_comment_reply.csv")
write_csv(nodes_cc, "nodes_comment_reply.csv")



```

Thread → Commento → Parola (Multilayer)
```{r}

edges_tc <- comments_with_threads %>%
  mutate(Source = paste0("T_", thread),
         Target = paste0("C_", comment_id),
         layer = "thread-comment") %>%
  select(Source, Target, layer)

comment_words <- comments_with_threads %>%
  select(comment_id, Cleaned_Comment) %>%
  unnest_tokens(word, Cleaned_Comment) %>%
  filter(str_length(word) > 2) %>%
  anti_join(stop_words)

edges_cw <- comment_words %>%
  mutate(Source = paste0("C_", comment_id),
         Target = paste0("W_", word),
         layer = "comment-word") %>%
  select(Source, Target, layer)

edges_multilayer <- bind_rows(edges_tc, edges_cw)

nodes_multilayer <- tibble(Id = unique(c(edges_multilayer$Source, edges_multilayer$Target))) %>%
  mutate(
    type = case_when(
      str_starts(Id, "T_") ~ "Thread",
      str_starts(Id, "C_") ~ "Comment",
      str_starts(Id, "W_") ~ "Word"
    ),
    Label = Id
  )

write_csv(edges_multilayer, "edges_multilayer.csv")
write_csv(nodes_multilayer, "nodes_multilayer.csv")

```

Autore → Parola
```{r}

author_words <- comments_with_threads %>%
  select(author.x, Cleaned_Comment) %>%
  unnest_tokens(word, Cleaned_Comment) %>%
  filter(str_length(word) > 2) %>%
  anti_join(stop_words)

edges_aw <- author_words %>%
  mutate(Source = paste0("U_", author.x),
         Target = paste0("W_", word)) %>%
  select(Source, Target) %>%
  distinct()

nodes_aw <- tibble(Id = unique(c(edges_aw$Source, edges_aw$Target))) %>%
  mutate(
    type = case_when(
      str_starts(Id, "U_") ~ "User",
      str_starts(Id, "W_") ~ "Word"
    ),
    Label = Id
  )

write_csv(edges_aw, "edges_author_word.csv")
write_csv(nodes_aw, "nodes_author_word.csv")

```

Autore → Thread
```{r}

edges_at <- comments_with_threads %>%
  mutate(Source = paste0("U_", author.x),
         Target = paste0("T_", thread)) %>%
  select(Source, Target) %>%
  distinct()

nodes_at <- tibble(Id = unique(c(edges_at$Source, edges_at$Target))) %>%
  mutate(
    type = case_when(
      str_starts(Id, "U_") ~ "User",
      str_starts(Id, "T_") ~ "Thread"
    ),
    Label = Id
  )

write_csv(edges_at, "edges_author_thread.csv")
write_csv(nodes_at, "nodes_author_thread.csv")

```


